### ISSUE TITLE
[Design] Lack of contrast between UTXO nodes and Transaction nodes

### ISSUE THREAD

**Issue by Janaka-Steph** [sapio-lang/sapio-studio#2]
On the diagram canvas, the transaction and output diagram entities are too visually similar. The trapezoid shape is simply reversed. It would be preferable to be able to distinguish a transaction from an output at first glance.
The diagram would be easier to read if the shapes were really different. One entity could have sharp corners while the other one a more rounded shape.

**Comment by JeremyRubin** [comment]
good point. I previously had utxos as circles, but the issue is that if the information is e.g. 100 pixels wide by 30 pixels high, a circle takes up a full r=50px circular area (7500 px) v.s 100*30 pixels = 3000px, so it takes up more than twice the area. Even worse, because of spherical packing problem, it's really closer to a 100x100 = 10,000 px bounding box, so greater than 3x the area to display the same info.

rectangles end up being essentially optimal unless we do something more clever, so this one is a bit easier said than done, but I agree it would be a major improvement for things to be more visually distinct.

**Comment by Janaka-Steph** [comment]
Yes, it doesn't have to be circular shapes, but simply rounded corners. Rounded enough to be easy to distinguish.

**Comment by JeremyRubin** [comment]
food for thought

https://www.conceptdraw.com/How-To-Guide/flowchart-design

![](https://www.conceptdraw.com/solution-park/resource/images/solutions/flowcharts/Flowchart-Design-Elements-Flowcharts-Rapid-Draw.png)

**Comment by JeremyRubin** [comment]
resolved
