### ISSUE TITLE
Hot reload loses contract state

### ISSUE THREAD

**Issue by Janaka-Steph** [sapio-lang/sapio-studio#5]
When writing code, the hot reload functionality results in the diagram and all contract state to be lost, which makes development experience difficult. As a quick fix, can I attach a contract ABI so that it is reloaded automatically?

**Comment by JeremyRubin** [comment]
Maybe just set it up so that under the "save" tab you have a button you can click "cache" that saves the current JSON to be auto-reloaded after the next hot reload?

That way if you are working on how a specific contract looks, you can more easily switch to it by generating it and clicking cache rather than having to e.g. change the codebase.

**Comment by JeremyRubin** [comment]
FIxed for development purposes -- the electron app now saves the most recently created contract so you can "reload" it from arguments.

TODO would be to cache the exact contract state instead.
